### ISSUE TITLE
Param comments that should be proper documentation

### ISSUE THREAD

**Issue by jlstevens** [ioam/param#94] opened 2015-02-22 16:53 UTC
In ``parameterized.py`` I am finding documentation that no one is likely to ever find unless they already know it is there. 

For instance there is an *Overview of Parameters for programmers*  which isn't in a docstring (written up in comments)  that is presented in the middle of the file.

Generally, now that param is a separate project with a dedicated website, I think such information should move there if you want people to understand param better while also making the actual code shorter and clearer.

**Comment by ceball** [comment] 2015-02-22 18:46
Duplicate of #89.

**Closed** 2015-02-22 18:45 UTC
Labels: task

**Comment by jlstevens** [comment] 2015-02-22 19:25
I'm not sure this is an actual duplicate - the other issue doesn't say anything about promoting these comments to real documentation.

**Comment by ceball** [comment] 2015-02-22 19:38
It doesn't just say some are "out of date", it says there's a variety of problems. Promoting some comments to docstrings or a manual of some sort is covered by the "etc" in my sentence ;)
